import { ToolDefinition, FileFormat } from '@fileconverter/shared-types';

export const ALL_TOOLS: ToolDefinition[] = [
  // --- PDF Primary & Conversion Tools ---
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Convert PDF documents into editable Word (.docx) documents with layout preservation.',
    category: 'convert',
    inputFormats: ['PDF'],
    outputFormats: ['DOCX'],
    executionModes: ['backend', 'local'],
    preferredMode: 'backend',
    priority: 100,
    icon: 'FileText',
    capabilities: ['single', 'batch'],
    slug: 'pdf-to-word',
    seoTitle: 'PDF to Word Converter — Free, Fast & Private',
    seoDescription: 'Convert your PDF files to editable Microsoft Word DOCX documents instantly.',
    explanation: 'Extracts formatted text, tables, and images from your PDF to create an editable Word document.',
    faq: [
      { q: 'Will the original layout be preserved?', a: 'Yes, text formatting, images, and structural hierarchy are retained.' },
      { q: 'Is my document private?', a: 'All temporary files are processed in isolated sandbox memory and deleted immediately after delivery.' }
    ]
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    description: 'Render every PDF page into high-resolution JPG images with selectable DPI quality.',
    category: 'convert',
    inputFormats: ['PDF'],
    outputFormats: ['JPEG'],
    executionModes: ['local', 'backend'],
    preferredMode: 'local',
    priority: 95,
    icon: 'Image',
    capabilities: ['single', 'batch', 'target-size'],
    slug: 'pdf-to-jpg',
    seoTitle: 'PDF to JPG Converter — High Quality, Browser-First',
    seoDescription: 'Extract high quality JPG photos and pages from any PDF directly in your browser.',
    explanation: 'Renders PDF pages directly in your browser using WebAssembly and PDF.js without sending data to servers.',
    faq: [
      { q: 'Can I choose the output image quality?', a: 'Yes, select from standard 150 DPI up to ultra-sharp 300 DPI.' },
      { q: 'Does it process multi-page PDFs?', a: 'Yes, all pages are exported individually or packaged in a neat ZIP archive.' }
    ]
  },
  {
    id: 'pdf-to-png',
    name: 'PDF to PNG',
    description: 'Convert PDF pages into crystal-clear lossless PNG images with alpha background support.',
    category: 'convert',
    inputFormats: ['PDF'],
    outputFormats: ['PNG'],
    executionModes: ['local', 'backend'],
    preferredMode: 'local',
    priority: 90,
    icon: 'ImagePlus',
    capabilities: ['single', 'batch'],
    slug: 'pdf-to-png',
    seoTitle: 'PDF to PNG Converter — Lossless & Private',
    seoDescription: 'Convert PDF documents to crisp lossless PNG pictures entirely on your device.',
    explanation: 'Generates lossless PNGs for charts, vectors, and text without compression artifacts.',
    faq: [
      { q: 'Does PNG support transparent backgrounds?', a: 'Yes, if the source PDF has no background fill, transparent PNGs are generated.' }
    ]
  },

  // --- PDF Editing & Organization Tools ---
  {
    id: 'edit-pdf',
    name: 'Edit PDF',
    description: 'Add text, images, signatures, freehand drawings, shapes, whiteout, and annotations directly in your browser.',
    category: 'edit',
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    executionModes: ['local'],
    preferredMode: 'local',
    priority: 85,
    icon: 'PenTool',
    capabilities: ['single'],
    slug: 'edit-pdf',
    seoTitle: 'Online PDF Editor — Add Text, Signatures, Shapes & Redact',
    seoDescription: 'Full-featured free PDF editor in your browser. Annotate, sign, fill forms, and export instantly.',
    explanation: 'A full vector canvas allows annotating, modifying, signing, and drawing directly onto PDF pages.',
    faq: [
      { q: 'Is my sensitive PDF safe?', a: '100% private. All edits occur locally in your browser memory.' }
    ]
  },
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Reduce PDF file size intelligently with target size matching and DPI re-sampling.',
    category: 'compress',
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    executionModes: ['local', 'backend'],
    preferredMode: 'local',
    priority: 80,
    icon: 'Minimize2',
    capabilities: ['single', 'batch', 'target-size'],
    slug: 'compress-pdf',
    seoTitle: 'Compress PDF — Smart Target File Size Compression',
    seoDescription: 'Reduce PDF size by up to 90% without sacrificing text readability. Set custom target size.',
    explanation: 'Optimizes embedded raster images, cleans redundant font streams, and compresses structural object streams.',
    faq: [
      { q: 'Can I specify an exact target size like 2 MB?', a: 'Yes! Our smart target size algorithm iterates compression levels to meet your target.' }
    ]
  },
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Combine multiple PDF files into one seamless document with custom page reordering.',
    category: 'organize',
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    executionModes: ['local'],
    preferredMode: 'local',
    priority: 78,
    icon: 'Layers',
    capabilities: ['batch'],
    slug: 'merge-pdf',
    seoTitle: 'Merge PDF Files Online — Free & Instant',
    seoDescription: 'Combine multiple PDFs into a single organized document in seconds right in your browser.',
    explanation: 'Merges PDF streams effortlessly while preserving bookmarks, outlines, and page orientation.',
    faq: [
      { q: 'Is there a limit on how many PDFs I can merge?', a: 'Process up to 100 PDFs simultaneously in your browser.' }
    ]
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    description: 'Separate one PDF into individual pages or custom page ranges instantly.',
    category: 'organize',
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    executionModes: ['local'],
    preferredMode: 'local',
    priority: 75,
    icon: 'Scissors',
    capabilities: ['single'],
    slug: 'split-pdf',
    seoTitle: 'Split PDF Pages — Extract Custom Ranges Instantly',
    seoDescription: 'Extract specific pages or break a PDF into separate files with visual thumbnail preview.',
    explanation: 'Select individual page numbers, odd/even ranges, or extract all pages into separate documents.',
    faq: [
      { q: 'Can I preview thumbnails before splitting?', a: 'Yes, visual page previews allow one-click page selection.' }
    ]
  },
  {
    id: 'ocr-pdf',
    name: 'OCR PDF',
    description: 'Turn scanned PDFs and images into searchable, selectable text using in-browser WebAssembly OCR.',
    category: 'ocr',
    inputFormats: ['PDF', 'JPEG', 'PNG', 'TIFF', 'WebP'],
    outputFormats: ['PDF', 'TXT'],
    executionModes: ['local', 'backend'],
    preferredMode: 'local',
    priority: 72,
    icon: 'ScanText',
    capabilities: ['single', 'batch'],
    slug: 'ocr-pdf',
    seoTitle: 'OCR PDF Online — Convert Scans to Searchable Text',
    seoDescription: 'Make scanned documents searchable with browser-based neural OCR engine.',
    explanation: 'Scans pages without readable text layers, runs neural optical character recognition, and embeds invisible searchable text.',
    faq: [
      { q: 'What languages are supported?', a: 'English, Spanish, French, German, Chinese, Japanese, and more.' }
    ]
  },
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    description: 'Permanently rotate all or specific PDF pages by 90, 180, or 270 degrees.',
    category: 'organize',
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    executionModes: ['local'],
    preferredMode: 'local',
    priority: 65,
    icon: 'RotateCw',
    capabilities: ['single', 'batch'],
    slug: 'rotate-pdf',
    seoTitle: 'Rotate PDF Pages — 90°, 180°, 270° Orientation Fix',
    seoDescription: 'Rotate upside-down or sideways PDF pages permanently with instant download.',
    explanation: 'Adjusts page rotation matrices cleanly without re-compressing or degrading page assets.',
    faq: []
  },
  {
    id: 'protect-pdf',
    name: 'Protect PDF',
    description: 'Encrypt PDF documents with 256-bit AES standard password protection.',
    category: 'security',
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    executionModes: ['local', 'backend'],
    preferredMode: 'local',
    priority: 60,
    icon: 'Lock',
    capabilities: ['single'],
    slug: 'protect-pdf',
    seoTitle: 'Password Protect PDF — 256-bit AES Encryption',
    seoDescription: 'Secure your confidential PDF documents with strong encryption directly in your browser.',
    explanation: 'Applies cryptographic security to lock reading or editing of sensitive documents.',
    faq: []
  },
  {
    id: 'unlock-pdf',
    name: 'Unlock PDF',
    description: 'Remove password and restriction locks from PDFs with provided decryption key.',
    category: 'security',
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    executionModes: ['local'],
    preferredMode: 'local',
    priority: 58,
    icon: 'Unlock',
    capabilities: ['single'],
    slug: 'unlock-pdf',
    seoTitle: 'Unlock PDF — Remove Password Protection',
    seoDescription: 'Decrypt and remove security restrictions from authorized PDF documents.',
    explanation: 'Decodes password-locked documents and re-saves an unrestricted version for easy sharing.',
    faq: []
  },
  {
    id: 'watermark-pdf',
    name: 'Watermark PDF',
    description: 'Add custom text or image watermarks with adjustable opacity, angle, and position.',
    category: 'edit',
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    executionModes: ['local'],
    preferredMode: 'local',
    priority: 55,
    icon: 'Stamp',
    capabilities: ['single', 'batch'],
    slug: 'watermark-pdf',
    seoTitle: 'Watermark PDF — Add Custom Stamps & Confidential Markers',
    seoDescription: 'Stamp PDFs with custom watermark text, diagonal angles, and transparent branding.',
    explanation: 'Applies vector watermarks on all pages across the entire document in one step.',
    faq: []
  },
  {
    id: 'remove-pdf-metadata',
    name: 'Remove PDF Metadata',
    description: 'Strip hidden author, creator software, GPS location, and editing history.',
    category: 'security',
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    executionModes: ['local'],
    preferredMode: 'local',
    priority: 50,
    icon: 'ShieldCheck',
    capabilities: ['single', 'batch'],
    slug: 'remove-pdf-metadata',
    seoTitle: 'Remove PDF Metadata — Sanitize Documents for Privacy',
    seoDescription: 'Wipe all internal metadata, author names, creation dates, and edit trails from PDFs.',
    explanation: 'Purges info dictionary, XMP metadata streams, and document creation markers.',
    faq: []
  },

  // --- Image Primary & Conversion Tools ---
  {
    id: 'jpg-to-png',
    name: 'JPG to PNG',
    description: 'Convert JPG images to lossless PNG format with transparent canvas readiness.',
    category: 'convert',
    inputFormats: ['JPEG'],
    outputFormats: ['PNG'],
    executionModes: ['local'],
    preferredMode: 'local',
    priority: 100,
    icon: 'Image',
    capabilities: ['single', 'batch', 'workflow'],
    slug: 'jpg-to-png',
    seoTitle: 'JPG to PNG Converter — 100% Free & Lossless',
    seoDescription: 'Convert JPG photos to PNG format instantly in your browser with no quality loss.',
    explanation: 'Decodes JPEG raster frames and stores them as uncompressed PNG bitstreams.',
    faq: []
  },
  {
    id: 'jpg-to-webp',
    name: 'JPG to WebP',
    description: 'Convert JPG to modern high-efficiency WebP format saving up to 40% size.',
    category: 'convert',
    inputFormats: ['JPEG'],
    outputFormats: ['WebP'],
    executionModes: ['local'],
    preferredMode: 'local',
    priority: 95,
    icon: 'Sparkles',
    capabilities: ['single', 'batch', 'target-size', 'workflow'],
    slug: 'jpg-to-webp',
    seoTitle: 'JPG to WebP Converter — Next-Gen Web Optimization',
    seoDescription: 'Convert JPGs to lightweight WebP files for lightning-fast website loading.',
    explanation: 'Uses modern WebP predictive encoding to maximize quality while drastically cutting bytes.',
    faq: []
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    description: 'Transform JPG images into high quality multi-page or single-page PDF files.',
    category: 'convert',
    inputFormats: ['JPEG'],
    outputFormats: ['PDF'],
    executionModes: ['local'],
    preferredMode: 'local',
    priority: 90,
    icon: 'FileUp',
    capabilities: ['single', 'batch'],
    slug: 'jpg-to-pdf',
    seoTitle: 'JPG to PDF Converter — Turn Images into PDF',
    seoDescription: 'Convert one or dozens of JPG images into a clean, print-ready PDF document.',
    explanation: 'Embeds full resolution JPEG streams inside standard PDF vector pages.',
    faq: []
  },

  {
    id: 'png-to-jpg',
    name: 'PNG to JPG',
    description: 'Convert PNG graphics and screenshots to lightweight JPG pictures.',
    category: 'convert',
    inputFormats: ['PNG'],
    outputFormats: ['JPEG'],
    executionModes: ['local'],
    preferredMode: 'local',
    priority: 100,
    icon: 'Image',
    capabilities: ['single', 'batch', 'workflow', 'target-size'],
    slug: 'png-to-jpg',
    seoTitle: 'PNG to JPG Converter — Fast & Private',
    seoDescription: 'Convert heavy PNGs to standard lightweight JPGs with adjustable quality and background color.',
    explanation: 'Flattens transparency smoothly onto clean background canvas and produces optimal JPG output.',
    faq: []
  },
  {
    id: 'png-to-webp',
    name: 'PNG to WebP',
    description: 'Convert PNG to WebP with transparent alpha channel preservation.',
    category: 'convert',
    inputFormats: ['PNG'],
    outputFormats: ['WebP'],
    executionModes: ['local'],
    preferredMode: 'local',
    priority: 95,
    icon: 'Sparkles',
    capabilities: ['single', 'batch', 'workflow', 'target-size'],
    slug: 'png-to-webp',
    seoTitle: 'PNG to WebP Converter — Transparent Alpha Supported',
    seoDescription: 'Convert transparent PNGs to super small WebP images without losing transparency.',
    explanation: 'Uses WebP lossless or lossy alpha compression to shrink PNGs by up to 70%.',
    faq: []
  },
  {
    id: 'png-to-pdf',
    name: 'PNG to PDF',
    description: 'Package PNG graphics and document scans into a polished PDF file.',
    category: 'convert',
    inputFormats: ['PNG'],
    outputFormats: ['PDF'],
    executionModes: ['local'],
    preferredMode: 'local',
    priority: 90,
    icon: 'FileUp',
    capabilities: ['single', 'batch'],
    slug: 'png-to-pdf',
    seoTitle: 'PNG to PDF Converter — Free Online Tool',
    seoDescription: 'Convert PNG images to standard PDF format with custom page margins and orientation.',
    explanation: 'Encapsulates PNG data seamlessly into structured PDF pages.',
    faq: []
  },

  {
    id: 'webp-to-jpg',
    name: 'WebP to JPG',
    description: 'Convert WebP images back into universally compatible JPG format.',
    category: 'convert',
    inputFormats: ['WebP'],
    outputFormats: ['JPEG'],
    executionModes: ['local'],
    preferredMode: 'local',
    priority: 100,
    icon: 'Image',
    capabilities: ['single', 'batch', 'workflow'],
    slug: 'webp-to-jpg',
    seoTitle: 'WebP to JPG Converter — Universal Compatibility',
    seoDescription: 'Turn WebP web files into standard JPG photos viewable on any device or software.',
    explanation: 'Decodes WebP frames and converts to universal JPEG standards.',
    faq: []
  },
  {
    id: 'webp-to-png',
    name: 'WebP to PNG',
    description: 'Convert WebP to lossless PNG format with transparent background.',
    category: 'convert',
    inputFormats: ['WebP'],
    outputFormats: ['PNG'],
    executionModes: ['local'],
    preferredMode: 'local',
    priority: 95,
    icon: 'ImagePlus',
    capabilities: ['single', 'batch', 'workflow'],
    slug: 'webp-to-png',
    seoTitle: 'WebP to PNG Converter — Transparent Alpha',
    seoDescription: 'Extract PNG format from WebP graphics with 100% pixel fidelity.',
    explanation: 'Restores full bitmap pixel representation from WebP containers.',
    faq: []
  },
  {
    id: 'webp-to-pdf',
    name: 'WebP to PDF',
    description: 'Combine WebP pictures into a clean PDF document.',
    category: 'convert',
    inputFormats: ['WebP'],
    outputFormats: ['PDF'],
    executionModes: ['local'],
    preferredMode: 'local',
    priority: 90,
    icon: 'FileUp',
    capabilities: ['single', 'batch'],
    slug: 'webp-to-pdf',
    seoTitle: 'WebP to PDF Converter',
    seoDescription: 'Turn WebP images into portable PDF files.',
    explanation: 'Draws WebP graphics into vector PDF pages.',
    faq: []
  },

  {
    id: 'heic-to-jpg',
    name: 'HEIC to JPG',
    description: 'Convert Apple iPhone HEIC/HEIF photos to standard JPG format.',
    category: 'convert',
    inputFormats: ['HEIC', 'HEIF'],
    outputFormats: ['JPEG'],
    executionModes: ['local', 'backend'],
    preferredMode: 'local',
    priority: 100,
    icon: 'Smartphone',
    capabilities: ['single', 'batch'],
    slug: 'heic-to-jpg',
    seoTitle: 'HEIC to JPG Converter — Convert iPhone Photos Instantly',
    seoDescription: 'Convert Apple iOS HEIC photos to compatible JPG images locally in your browser.',
    explanation: 'Decodes High Efficiency Image Container frames using WebAssembly and creates universal JPGs.',
    faq: []
  },
  {
    id: 'heic-to-png',
    name: 'HEIC to PNG',
    description: 'Convert iPhone HEIC photos to lossless high-resolution PNG images.',
    category: 'convert',
    inputFormats: ['HEIC', 'HEIF'],
    outputFormats: ['PNG'],
    executionModes: ['local', 'backend'],
    preferredMode: 'local',
    priority: 95,
    icon: 'ImagePlus',
    capabilities: ['single', 'batch'],
    slug: 'heic-to-png',
    seoTitle: 'HEIC to PNG Converter — Lossless iPhone Image Export',
    seoDescription: 'Convert HEIC/HEIF images to uncompressed PNGs directly on your computer or mobile.',
    explanation: 'Decodes HEIC bitstream into transparent or opaque PNG.',
    faq: []
  },
  {
    id: 'heic-to-pdf',
    name: 'HEIC to PDF',
    description: 'Turn HEIC/HEIF photos into a PDF document.',
    category: 'convert',
    inputFormats: ['HEIC', 'HEIF'],
    outputFormats: ['PDF'],
    executionModes: ['local', 'backend'],
    preferredMode: 'local',
    priority: 90,
    icon: 'FileUp',
    capabilities: ['single', 'batch'],
    slug: 'heic-to-pdf',
    seoTitle: 'HEIC to PDF Converter — Turn iPhone Photos into PDF',
    seoDescription: 'Convert multiple HEIC iPhone photos into a neat PDF document.',
    explanation: 'Converts HEIC images and places them on clean PDF pages.',
    faq: []
  },

  {
    id: 'avif-to-jpg',
    name: 'AVIF to JPG',
    description: 'Convert next-gen AVIF images to standard JPG format.',
    category: 'convert',
    inputFormats: ['AVIF'],
    outputFormats: ['JPEG'],
    executionModes: ['local', 'backend'],
    preferredMode: 'local',
    priority: 100,
    icon: 'Image',
    capabilities: ['single', 'batch'],
    slug: 'avif-to-jpg',
    seoTitle: 'AVIF to JPG Converter',
    seoDescription: 'Convert AV1 image file format (AVIF) to universally compatible JPG.',
    explanation: 'Decodes AVIF container frames and creates clean JPEG output.',
    faq: []
  },
  {
    id: 'avif-to-png',
    name: 'AVIF to PNG',
    description: 'Convert AVIF images to PNG with transparency support.',
    category: 'convert',
    inputFormats: ['AVIF'],
    outputFormats: ['PNG'],
    executionModes: ['local', 'backend'],
    preferredMode: 'local',
    priority: 95,
    icon: 'ImagePlus',
    capabilities: ['single', 'batch'],
    slug: 'avif-to-png',
    seoTitle: 'AVIF to PNG Converter',
    seoDescription: 'Convert AVIF files to crisp PNG format.',
    explanation: 'Extracts full RGB/RGBA bitmap from AVIF image stream.',
    faq: []
  },

  {
    id: 'tiff-to-jpg',
    name: 'TIFF to JPG',
    description: 'Convert professional TIFF/TIF scans and raw photos to lightweight JPG.',
    category: 'convert',
    inputFormats: ['TIFF'],
    outputFormats: ['JPEG'],
    executionModes: ['local', 'backend'],
    preferredMode: 'local',
    priority: 100,
    icon: 'Image',
    capabilities: ['single', 'batch'],
    slug: 'tiff-to-jpg',
    seoTitle: 'TIFF to JPG Converter — Convert TIF Files',
    seoDescription: 'Convert multi-page or single-page TIFF files to compact JPG images.',
    explanation: 'Decodes TIFF raster data with format rescue fallback for rare compressions.',
    faq: []
  },
  {
    id: 'tiff-to-pdf',
    name: 'TIFF to PDF',
    description: 'Convert multi-page TIFF scanned documents into a single organized PDF.',
    category: 'convert',
    inputFormats: ['TIFF'],
    outputFormats: ['PDF'],
    executionModes: ['local', 'backend'],
    preferredMode: 'local',
    priority: 90,
    icon: 'FileUp',
    capabilities: ['single', 'batch'],
    slug: 'tiff-to-pdf',
    seoTitle: 'TIFF to PDF Converter — Turn TIFF Scans into PDF',
    seoDescription: 'Convert multi-page TIFF scans to standard PDF documents.',
    explanation: 'Packages each TIFF page frame into a corresponding PDF page.',
    faq: []
  },

  {
    id: 'gif-to-webp',
    name: 'GIF to WebP',
    description: 'Convert animated or static GIFs to smooth, lightweight WebP animations.',
    category: 'convert',
    inputFormats: ['GIF'],
    outputFormats: ['WebP'],
    executionModes: ['local'],
    preferredMode: 'local',
    priority: 100,
    icon: 'Film',
    capabilities: ['single', 'batch'],
    slug: 'gif-to-webp',
    seoTitle: 'GIF to WebP Converter — Reduce GIF Size by 80%',
    seoDescription: 'Convert heavy GIFs to modern animated WebP files.',
    explanation: 'Re-encodes GIF frames with 24-bit color depth and superior compression.',
    faq: []
  },
  {
    id: 'svg-to-png',
    name: 'SVG to PNG',
    description: 'Rasterize vector SVG files into crisp PNG images at any desired resolution.',
    category: 'convert',
    inputFormats: ['SVG'],
    outputFormats: ['PNG'],
    executionModes: ['local'],
    preferredMode: 'local',
    priority: 100,
    icon: 'Maximize',
    capabilities: ['single', 'batch'],
    slug: 'svg-to-png',
    seoTitle: 'SVG to PNG Converter — High Resolution Rasterizer',
    seoDescription: 'Render vector SVG illustrations to high-DPI PNGs with transparency.',
    explanation: 'Draws vector curves with crisp anti-aliasing onto canvas and outputs lossless PNG.',
    faq: []
  },
  {
    id: 'svg-to-pdf',
    name: 'SVG to PDF',
    description: 'Convert SVG vector illustrations into scalable vector PDF documents.',
    category: 'convert',
    inputFormats: ['SVG'],
    outputFormats: ['PDF'],
    executionModes: ['local'],
    preferredMode: 'local',
    priority: 90,
    icon: 'FileUp',
    capabilities: ['single', 'batch'],
    slug: 'svg-to-pdf',
    seoTitle: 'SVG to PDF Converter — Scalable Vector Output',
    seoDescription: 'Convert SVG vector graphics into print-ready PDF files.',
    explanation: 'Maps SVG vectors into native PDF vector draw operations.',
    faq: []
  },

  // --- Image Utilities & Transformation Tools ---
  {
    id: 'compress-image',
    name: 'Compress Image',
    description: 'Shrink JPG, PNG, and WebP image file sizes with real-time before/after preview.',
    category: 'compress',
    inputFormats: ['JPEG', 'PNG', 'WebP', 'AVIF', 'HEIC', 'TIFF', 'BMP'],
    outputFormats: ['JPEG', 'PNG', 'WebP'],
    executionModes: ['local'],
    preferredMode: 'local',
    priority: 85,
    icon: 'Minimize2',
    capabilities: ['single', 'batch', 'target-size', 'before-after', 'workflow'],
    slug: 'compress-image',
    seoTitle: 'Image Compressor — Smart Compression with Target Size',
    seoDescription: 'Compress images by up to 90% with instant visual before & after slider comparison.',
    explanation: 'Uses psycho-visual perceptual quantization to discard invisible noise while preserving sharpness.',
    faq: []
  },
  {
    id: 'resize-image',
    name: 'Resize Image',
    description: 'Change pixel dimensions or percentage scale with aspect ratio lock.',
    category: 'edit',
    inputFormats: ['JPEG', 'PNG', 'WebP', 'AVIF', 'HEIC', 'TIFF', 'BMP', 'GIF', 'SVG'],
    outputFormats: ['JPEG', 'PNG', 'WebP'],
    executionModes: ['local'],
    preferredMode: 'local',
    priority: 80,
    icon: 'Maximize2',
    capabilities: ['single', 'batch', 'workflow'],
    slug: 'resize-image',
    seoTitle: 'Resize Image Online — Exact Pixel Dimensions & Scaling',
    seoDescription: 'Resize photos to exact width, height, or percentage while maintaining crisp clarity.',
    explanation: 'High quality bicubic/lanczos canvas sampling for downscaling and upscaling.',
    faq: []
  },
  {
    id: 'crop-image',
    name: 'Crop Image',
    description: 'Cut and frame images with customizable aspect ratio presets (16:9, 1:1, 4:3) or freeform box.',
    category: 'edit',
    inputFormats: ['JPEG', 'PNG', 'WebP', 'AVIF', 'HEIC', 'TIFF', 'BMP'],
    outputFormats: ['JPEG', 'PNG', 'WebP'],
    executionModes: ['local'],
    preferredMode: 'local',
    priority: 75,
    icon: 'Crop',
    capabilities: ['single', 'workflow'],
    slug: 'crop-image',
    seoTitle: 'Crop Image Online — Aspect Ratio & Freeform Cropping',
    seoDescription: 'Crop pictures easily with social media presets or custom pixel selection.',
    explanation: 'Instant interactive cropping overlay with lossless sub-region extraction.',
    faq: []
  },
  {
    id: 'remove-image-metadata',
    name: 'Remove EXIF & GPS Metadata',
    description: 'Strip camera info, shutter speed, date, and geolocation coordinates for 100% privacy.',
    category: 'security',
    inputFormats: ['JPEG', 'PNG', 'WebP', 'HEIC', 'TIFF'],
    outputFormats: ['JPEG', 'PNG', 'WebP'],
    executionModes: ['local'],
    preferredMode: 'local',
    priority: 70,
    icon: 'ShieldCheck',
    capabilities: ['single', 'batch', 'workflow'],
    slug: 'remove-image-metadata',
    seoTitle: 'Remove EXIF & GPS Metadata from Photos — 100% Private',
    seoDescription: 'Wipe camera specs, location coordinates, and metadata from your images.',
    explanation: 'Reconstructs clean image bitstreams without EXIF header blocks or GPS tags.',
    faq: []
  },
  {
    id: 'qr-generator',
    name: 'QR Code Generator',
    description: 'Create custom vector QR codes for URLs, Wi-Fi networks, text, contacts, emails, and SMS.',
    category: 'utility',
    inputFormats: ['RAW'],
    outputFormats: ['PNG', 'SVG', 'PDF'],
    executionModes: ['local'],
    preferredMode: 'local',
    priority: 85,
    icon: 'QrCode',
    capabilities: ['single'],
    slug: 'qr-generator',
    seoTitle: 'QR Code Generator — Free, Custom Vector & 100% Private',
    seoDescription: 'Generate custom styled QR codes with high-res PNG, SVG vector, and PDF export.',
    explanation: 'Creates instant client-side QR codes with customizable color schemes and error resilience.',
    faq: []
  },
  {
    id: 'qr-scanner',
    name: 'QR Code Scanner & Decoder',
    description: 'Decode QR codes and barcodes directly from uploaded image photos or documents.',
    category: 'utility',
    inputFormats: ['JPEG', 'PNG', 'WebP', 'AVIF', 'HEIC'],
    outputFormats: ['TXT'],
    executionModes: ['local'],
    preferredMode: 'local',
    priority: 80,
    icon: 'Scan',
    capabilities: ['single'],
    slug: 'qr-scanner',
    seoTitle: 'QR Code Scanner Online — Read QR from Images',
    seoDescription: 'Scan and decode QR codes from photos and documents directly in your browser.',
    explanation: 'Extracts encoded URLs, passwords, and text payloads without sending images to remote servers.',
    faq: []
  }
];

export function getToolById(id: string): ToolDefinition | undefined {
  return ALL_TOOLS.find(t => t.id === id);
}

export function getToolBySlug(slug: string): ToolDefinition | undefined {
  return ALL_TOOLS.find(t => t.slug === slug || t.id === slug);
}
